human_bones = ["b__ROOT__", "b__ROOT_bind__", "b__Spine0__", "b__Spine1__", "b__Spine2__", "b__Neck__", "b__Head__",
               "b__CAS_Glasses__", "b__L_Cheek__", "b__L_Squint__", "b__CAS_L_EyeArea__", "b__L_InBrow__",
               "b__L_MidBrow__", "b__L_OutBrow__", "b__CAS_L_EyeScale__", "b__L_LoLid__", "b__L_UpLid__", "b__L_Eye__",
               "b__R_Cheek__", "b__R_Squint__", "b__CAS_R_EyeArea__", "b__R_InBrow__", "b__R_MidBrow__",
               "b__R_OutBrow__", "b__CAS_R_EyeScale__", "b__R_LoLid__", "b__R_UpLid__", "b__R_Eye__",
               "b__CAS_NoseArea__", "b__CAS_NoseTip__", "b__CAS_NoseBridge__", "b__CAS_L_Nostril__",
               "b__CAS_R_Nostril__", "b__CAS_UpperMouthArea__", "b__L_Mouth__", "b__L_UpLip__", "b__R_Mouth__",
               "b__R_UpLip__", "b__UpLip__", "b__mouth_slot", "b__Jaw__", "b__CAS_LowerMouthArea__", "b__LoLip__",
               "b__L_LoLip__", "b__R_LoLip__", "b__CAS_JawComp__", "b__CAS_Chin__", "b__L_Earring_slot",
               "b__R_Earring_slot", "b__Neck_slot", "b__backNeck_slot", "b__L_chestTarget_slot",
               "b__L_shoulderbladeTarget_slot", "b__R_chestTarget_slot", "b__R_shoulderbladeTarget_slot",
               "b__R_Clavicle__", "b__R_ShoulderTarget_slot", "b__R_UpperArm__", "b__R_Forearm__",
               "b__R_ForearmTwist__", "b__R_Bracelet_slot", "b__R_Hand__", "b__R_Stigmata", "b__R_Thumb0__",
               "b__R_Thumb1__", "b__R_Thumb2__", "b__R_Pinky0__", "b__R_Pinky1__", "b__R_Pinky2__", "b__R_Ring0__",
               "b__R_Ring1__", "b__R_Ring2__", "b__R_Ring_slot", "b__R_Mid0__", "b__R_Mid1__", "b__R_Mid2__",
               "b__R_Index0__", "b__R_Index1__", "b__R_Index2__", "b__R_ForearmTarget_slot", "b__R_Elbow__",
               "b__R_ShoulderTwist__", "b__R_outShortSleeve_slot", "b__L_Clavicle__", "b__L_UpperArm__",
               "b__L_Forearm__", "b__L_ForearmTwist__", "b__L_Bracelet_slot", "b__L_Hand__", "b__L_Stigmata",
               "b__L_Thumb0__", "b__L_Thumb1__", "b__L_Thumb2__", "b__L_Index0__", "b__L_Index1__", "b__L_Index2__",
               "b__L_Mid0__", "b__L_Mid1__", "b__L_Mid2__", "b__L_Ring0__", "b__L_Ring1__", "b__L_Ring2__",
               "b__L_Ring_slot", "b__L_Pinky0__", "b__L_Pinky1__", "b__L_Pinky2__", "b__L_ForearmTarget_slot",
               "b__L_Elbow__", "b__L_ShoulderTwist__", "b__L_outShortSleeve_slot", "b__L_ShoulderTarget_slot",
               "b__R_ArmExportPole__", "b__L_ArmExportPole__", "b__R_HandDangle_slot", "b__L_HandDangle_slot",
               "b__CAS_L_Breast__", "b__L_breastTarget_slot", "b__L_frontTorsoTarget_slot",
               "b__L_sideBackTorsoTarget_slot", "b__CAS_R_Breast__", "b__R_breastTarget_slot",
               "b__R_frontTorsoTarget_slot", "b__R_sideBackTorsoTarget_slot", "b__R_BackTarget_slot",
               "b__L_BackTarget_slot", "b__Carry__", "b__R_carry_slot", "b__L_carry_slot", "b__L_backBellyTarget_slot",
               "b__L_BellyTarget_slot", "b__L_frontBellyTarget_slot", "b__R_backBellyTarget_slot",
               "b__R_BellyTarget_slot", "b__R_frontBellyTarget_slot", "b__L_lowBackTarget_slot",
               "b__R_lowBackTarget_slot", "b__Pelvis__", "b__L_Thigh__", "b__L_Calf__", "b__L_Foot__", "b__L_Toe__",
               "b__L_frontCalfTarget_slot", "b__L_inCalfTarget_slot", "b__L_KneeTarget_slot", "b__L_Skirt__",
               "b__L_ThighTwist__", "b__L_LegExportPole__", "b__L_outThighTarget_slot", "b__L_ThighFrontTarget_slot",
               "b__R_Thigh__", "b__R_Calf__", "b__R_Foot__", "b__R_Toe__", "b__R_frontCalfTarget_slot",
               "b__R_inCalfTarget_slot", "b__R_KneeTarget_slot", "b__R_Skirt__", "b__R_ThighTwist__",
               "b__R_LegExportPole__", "b__R_outThighTarget_slot", "b__R_ThighFrontTarget_slot",
               "b__L_ThighTarget_slot", "b__R_ThighTarget_slot", "b__R_Prop__", "b__L_Prop__", ]
